version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_DEBUG=production
    volumes:
      - .:/app
    expose:
      - "5000"  # Expose Flask's internal port, no need to map it to the host in production
    restart: unless-stopped
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Ensure this path is correct
      - ./web/static:/app/web/static        # Map the static folder for Nginx access
    depends_on:
      - flask-app
    restart: unless-stopped

networks:
  default:
    driver: bridge  # Ensure both containers share the same Docker network
